config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    stored_username = Rails.application.credentials.dig(:sidekiq, :username)
    stored_password = Rails.application.credentials.dig(:sidekiq, :password)

    username == stored_username && password == stored_password
  end

  mount Sidekiq::Web => "/sidekiq"

  get "adopts/index"
  get "adopts/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :dogs do
    resources :adopts, only: %i[new create index show destroy]
    post :adopt_dog, on: :member
    resources :walking_reservations, only: %i[new create show destroy]
  end

  resources :comments
  resources :walking_reservations, only: [:index]

  get "dogs/:id/requests", to: "adopts#requests", as: :dog_requests

  # Defines the root path route ("/")
  root "pages#home"
  get "about", to: "pages#about"

  resources :placements

  resources :adoption_applications

  resources :shifts

  resources :donations

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :reports, only: %i[new create]

  get "profile", to: "pages#profile"
  resources :volunteers do
    collection do
      post :create_event
    end
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_one_attached :avatar do |attachable|
        attachable.variant :thumb, resize_to_limit: [400, 200]
    end
    has_many :comments, as: :commentable, dependent: :nullify
    has_many :adopts, dependent: :destroy
    has_many :walking_reservations, dependent: :destroy
    belongs_to :user, optional: true

    validates :size,   inclusion: { in: %w[small medium large] }
    validates :sex,    inclusion: { in: %w[male female] }
    validates :name, presence: true
    validates :age_month, presence: true
    validates :breed, presence: true
    validates :diagnosis, presence: true, allow_blank: true

    enum :status, { available: 0, available_for_walk: 1, unavailable: 2, adopted: 3, archived: 4 }, default: :available

    enum :health_status, { healthy: 0, ill: 1, chronically_diseased: 2, under_treatment: 3 }, default: :healthy

    enum :agressivness, { mostly_calm: 0, calm: 1, mostly_agressive: 2, agressive: 3 }, default: :mostly_calm

    scope :with_assotiations, -> { includes(:dog, :user) }
    scope :recent_with_avatar_scope, -> {
        with_attached_avatar
        .order(created_at: :desc)
    }

    def self.recent_with_avatar(page = 1)
        recent_with_avatar_scope.page(page)
    end

    def self.ransackable_attributes(auth_object = nil)
        %w[name breed sex age_month size status health_status created_at]
    end

    def self.ransackable_associations(auth_object = nil)
        %w[user]
    end

    def diagnosis_pairs
        diagnosis.presence || {}
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    skip_before_action :authenticate_user!, only: %i[index show]

    before_action :authorize_dog, only: %i[new create]
    before_action :set_dog, only: %i[show edit update destroy adopt_dog]
    before_action :setup_comments_and_adopts, only: %i[show]

    def index
        @q = Dog.ransack(search_params)
        @dogs = Dogs::FilterQuery.call(
        search_params: search_params,
        page: params[:page],
        current_user: current_user
        )
    end

    def new
        @dog = Dog.new
    end

    def create
        @dog = Dog.new(dog_params)
        result = Dogs::CreateDogOrganizer.call(dog: @dog, params: params[:dog], current_user: @current_user)

        return redirect_to @dog, notice: t("success_create", thing: "Dog"), status: :see_other if result.success?

        flash.now[:alert] = result.error || t("failed_create", thing: "Dog")
        render :new, status: :unprocessable_entity
    end

    def show
        @adopts = policy_scope(Adopt).with_assotiations
    end

    def edit; end

    def update
        @dog.update!(dog_params)
        Dogs::ChangeStatus.call(dog: @dog)
        redirect_to @dog, notice: t("success_update", thing: "Dog"), status: :see_other
    rescue StandardError => e
        redirect_to dog_path(@dog), alert: e || t("failed_update", thing: "Dog")
    end

    def adopt_dog
        organizer = @dog.available? ? Adopts::AdoptDogOrganizer : Adopts::ReturnDogOrganizer

        result = organizer.call(
            dog: @dog,
            dog_attributes: params.require(:dog).permit(:status),
            adopt_id: params[:adopt_id],
            current_user: @current_user
        )

        if result.success?
            notice_key = @dog.available? ? "adopt.success.return" : "adopt.success.adopt"
            redirect_to dog_path(@dog), notice: t(notice_key), status: :see_other
        else
            flash.now[:alert] = result.errors || t("adopt.failed")
            render :show, status: :unprocessable_entity
        end
    end

    def destroy
        @dog.destroy
        redirect_to dogs_path, notice: t("success_destroy", thing: "Dog")
    rescue StandardError => e
        redirect_to dog_path(@dog), alert: e || t("failed_destroy", thing: "Dog")
    end


    private

    def search_params
        params.fetch(:q, {}).permit(
            :name_cont,
            :breed_cont,
            :sex_eq,
            :age_month_gteq,
            :age_month_lteq,
            :size_eq,
            :status_eq,
            :health_status_eq,
            :s
        )
    end

    def set_dog
        @dog = Dog.find(params[:id])
    end

    def authorize_dog
        authorize @dog || Dog.new
    end

    def dog_params
        params.require(:dog).permit(:name, :sex, :age_month, :size, :breed, :status, :avatar, :diagnosis, :health_status)
    end

    def setup_comments_and_adopts
        @comments = @dog.comments.includes(:user).order(created_at: :desc)
        @comment = @dog.comments.build
    end
end

app/helpers/dog_helper.rb
module DogHelper
  def render_field(label, value)
    return unless value.present?

    content_tag(:p) do
      concat content_tag(:span, "#{label}:", class: "fw-bold")
      concat " #{value}"
    end
  end

  def health_status_options
    Dog.health_statuses.map { |key, value| [key.humanize, key] }
  end

  def status_options
    Dog.statuses.map { |key, value| [key.humanize, key] }
  end

  def aggressiveness_options
    Dog.agressivnesses.map { |key, value| [key.humanize, key] }
  end

  def dog_status_options
    options = [
      ["All", ""],
      ["Available", "available"],
      ["Adopted", "adopted"],
      ["Available for walk", "available_for_walk"]
    ]

    options << ["Archived", "archived"] if current_user&.role != "user"
    options
  end
end

app/views/dogs/_adopt_button.html.erb
<% if current_user&.user? && @dog.status=="available" %>
    <% if @dog.adopts.exists?(user_id: current_user.id) %>
        <%= link_to "You have already sent an adoption request", dog_adopt_path(@dog), class: "btn btn-primary disabled" %>
    <% else %>
        <%= link_to "Adopt", new_dog_adopt_path(@dog), class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/dogs/_dog.html.erb
<article class="col p-0">
    <%= link_to dog_path(dog) do %>
        <div class="card">
            <% if dog.avatar.attached? %>
                <%= image_tag dog.avatar, height: 200, class: "object-fit-cover" %>
            <% else %>
                <%= image_tag "avatar.svg", height: 200, class: "object-fit-cover" %>
            <% end %>
            <div class="card-body d-flex flex-column gap-2">
                <h5 class="card-title"><%= dog.name %> (<%= dog.sex.humanize %>)</h5>
                <p class="card-text"><span class="fw-bold">Age:</span> <%= dog.age_month %> months</p>
                <p class="card-text"><span class="fw-bold">Size:</span> <%= dog.size %></p>
                <p class="card-text"><span class="fw-bold">Breed:</span> <%= dog.breed %></p>
                <p class="card-text"><span class="fw-bold">Status:</span> <%= dog.status.humanize %></p>
            </div>
        </div>
    <% end %>
</article>

app/views/dogs/_dog_form.html.erb
<%= form_with(model: @dog) do |form| %>
    <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :sex, class: "form-label" %>
        <%= form.select :sex, %w[male female], {}, { class: "form-select" } %>
    </div>
    <div class="mb-3">
        <%= form.label :age_month, class: "form-label" %>
        <%= form.text_field :age_month, class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :size, class: "form-label" %>
        <%= form.select :size, %w[small medium large], {}, { class: "form-select" } %>
    </div>
    <div class="mb-3">
        <%= form.label :breed, class: "form-label" %>
        <%= form.text_field :breed, class: "form-control" %>
    </div>

    <h4>Health Status and Treatment</h4>

    <div class="mb-3">
        <%= form.label :health_status, "Health Status", class: "form-label" %>
        <%= form.select :health_status, health_status_options, {}, { class: "form-select" } %>
    </div>

    <div class="mb-3">
        <%= form.label :disease_name, "Disease Name", class: "form-label" %>
        <%= form.text_field :disease_name, value: @dog.diagnosis&.dig("disease_name"), class: "form-control" %>
    </div>

    <h5>Medicine</h5>
    <div class="mb-3">
        <%= form.label :medicine_name, "Medicine Name", class: "form-label" %>
        <%= form.text_field :medicine_name, value: @dog.diagnosis&.dig("medicine_name"), class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.label :additional_info, "Additional Info", class: "form-label" %>
        <%= form.text_field :additional_info, value: @dog.diagnosis&.dig("additional_info"), class: "form-control" %>
    </div>

    <h5>Aggressiveness</h5>
    <div class="mb-3">
        <%= form.label :aggressiveness, "Aggressiveness", class: "form-label" %>
        <%= form.select :aggressiveness, aggressiveness_options, {}, { class: "form-select" }  %>
    </div>


    <div class="mb-3">
        <%= form.label :avatar, class: "form-label" %>
        <%= form.file_field :avatar, class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/dogs/_dog_health.html.erb
<% if diagnosis.present? %>
    <p><span class="fw-bold">Health Status:</span> <%= health_status.humanize %></p>
    <p><span class="fw-bold">Disease Name:</span> <%= diagnosis["disease_name"] %></p>
    <p><span class="fw-bold">Medicine Name:</span> <%= diagnosis["medicine_name"] %></p>
    <p><span class="fw-bold">Additional Info:</span> <%= diagnosis["additional_info"] %></p>
<% end %>

app/views/dogs/_dogs_collection.html.erb
<% if @dogs.any? %>
    <p class="text-muted mb-3">
    Found <%= @dogs.total_count %> <%= "dog".pluralize(@dogs.total_count) %>
    </p>
    <div class="row row-cols-1 auto-grid">
    <%= render @dogs %>
    </div>
    <%= paginate @dogs %>
<% else %>
    <div class="alert alert-info">
    No dogs found matching your criteria. Try adjusting your filters.
    </div>
<% end %>

app/views/dogs/_filters.html.erb
<div class="card mb-4">           <!-- 1. відкриваючий -->
    <div class="card-body">        <!-- 2. відкриваючий -->
    <h5 class="card-title">🔍 Filter Dogs</h5>
    <%= search_form_for @q, url: dogs_path, method: :get, html: { class: "row g-3" } do |f| %>

        <div class="col-md-3">
        <%= f.label :name_cont, "Name", class: "form-label" %>
        <%= f.search_field :name_cont,
            placeholder: "Search by name...",
            class: "form-control" %>
        </div>

        <div class="col-md-3">
        <%= f.label :breed_cont, "Breed", class: "form-label" %>
        <%= f.search_field :breed_cont,
            placeholder: "Search by breed...",
            class: "form-control" %>
        </div>

        <div class="col-md-2">
        <%= f.label :sex_eq, "Sex", class: "form-label" %>
        <%= f.select :sex_eq,
            options_for_select([
                ["All", ""],
                ["Male", "male"],
                ["Female", "female"]
            ], f.object.sex_eq),
            {},
            class: "form-select" %>
        </div>

        <div class="col-md-2">
        <%= f.label :size_eq, "Size", class: "form-label" %>
        <%= f.select :size_eq,
            options_for_select([
                ["All", ""],
                ["Small", "small"],
                ["Medium", "medium"],
                ["Large", "large"]
            ], f.object.size_eq),
            {},
            class: "form-select" %>
        </div>

        <div class="col-md-2">
        <%= f.label :status_eq, "Status", class: "form-label" %>
        <%= f.select :status_eq,
            options_for_select(dog_status_options, f.object.status_eq),
            {},
            class: "form-select" %>
        </div>

        <div class="col-md-2">
        <%= f.label :age_month_gteq, "Age from (months)", class: "form-label" %>
        <%= f.number_field :age_month_gteq,
            placeholder: "Min age",
            class: "form-control",
            min: 0 %>
        </div>

        <div class="col-md-2">
        <%= f.label :age_month_lteq, "Age to (months)", class: "form-label" %>
        <%= f.number_field :age_month_lteq,
            placeholder: "Max age",
            class: "form-control",
            min: 0 %>
        </div>

        <div class="col-md-3">
        <%= f.label :s, "Sort by", class: "form-label" %>
        <%= f.select :s,
            options_for_select([
                ["Newest first", "created_at desc"],
                ["Oldest first", "created_at asc"],
                ["Name A-Z", "name asc"],
                ["Name Z-A", "name desc"],
                ["Age: Young to Old", "age_month asc"],
                ["Age: Old to Young", "age_month desc"]
            ], f.object.sorts.first&.to_s),
            {},
            class: "form-select" %>
        </div>

        <div class="col-md-5 d-flex align-items-end">
        <%= f.submit "Search", class: "btn btn-primary me-2" %>
        <%= link_to "Clear", dogs_path, class: "btn btn-outline-secondary" %>
        </div>
    <% end %>
    </div>                          <!-- 2. закриваючий card-body -->
</div>                              <!-- 1. закриваючий card -->

app/views/dogs/edit.html.erb
<%= render "dogs/dog_form" %>

app/views/dogs/index.html.erb
<section class="back-img">
  <div class="container">
    <h1 class="text-center">Pets</h1>

    <% if policy(Dog.new).create? %>
      <%= link_to "New Dog", new_dog_path, class: "btn btn-primary my-3 d-block mx-auto" %>
    <% end %>

    <%= render "dogs/filters" %>

    <%= render "dogs/dogs_collection", dogs: @dogs %>
  </div>
</section>

app/views/dogs/new.html.erb
<section class="container">
    <% if policy(@dog).create? %>
        <h1>New Dog</h1>
        <%= render 'dog_form', dog: @dog %>
    <% end %>
</section>

app/views/dogs/show.html.erb
<section class="back-img">
    <div class="container">
    <div class=" d-flex flex-column flex-md-row col-md-6 pt-5 align-items-center gap-5 w-100">
        <div>
            <% if @dog.avatar.attached? %>
                <%= image_tag @dog.avatar, height: 300, class: "object-fit-cover rounded-4" %>
            <% else %>
                <%= image_tag "avatar.svg", height: 300, class: "object-fit-cover rounded-4" %>
            <% end %>
        </div>
        <div>
            <h1><%= @dog.name %></h1>
            <p><span class="fw-bold">Sex:</span> <%= @dog.sex %></p>
            <p><span class="fw-bold">Age:</span> <%= @dog.age_month %> months</p>
            <p><span class="fw-bold">Size:</span> <%= @dog.size %></p>
            <p><span class="fw-bold">Breed:</span> <%= @dog.breed %></p>
            <p><span class="fw-bold">Status:</span> <%= @dog.status.humanize %></p>
            <h4>Health Status and Treatment</h4>
            <%= render "dogs/dog_health", diagnosis: @dog.diagnosis, health_status: @dog.health_status.humanize %>
            <p><span class="fw-bold">Aggressiveness:</span> <%= @dog.agressivness.humanize %></p>
            <div class="d-flex gap-2 align-items-center">
                <% if policy(@dog).update? %>
                    <%= link_to "Edit", edit_dog_path(@dog), class: "btn btn-primary" %>
                <% end %>
                <%= link_to "Back", dogs_path, class: "btn btn-secondary" %>
                <% if policy(@dog).destroy? %>
                    <%= link_to "Delete", dog_path(@dog), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
                <% end %>
                <%= render "dogs/adopt_button", current_user=current_user %>
            </div>
        </div>
    </div>
    <div>
        <% if ["available_for_walk", "available"].include?(@dog.status) %>
            <%= link_to "Book a walk with this dog", new_dog_walking_reservation_path(@dog), class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="pt-5">
        <% if policy(Comment.new).create? %>
            <%= render "comments/new_comment", commentable_id: @dog.id, commentable_type: "Dog" %>
        <% end %>
        <%= render "comments/all_comments", dog: @dog %>
    </div>
</section>