config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    stored_username = Rails.application.credentials.dig(:sidekiq, :username)
    stored_password = Rails.application.credentials.dig(:sidekiq, :password)

    username == stored_username && password == stored_password
  end

  mount Sidekiq::Web => "/sidekiq"

  get "adopts/index"
  get "adopts/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :dogs do
    resources :adopts, only: %i[new create index show destroy]
    post :adopt_dog, on: :member
    resources :walking_reservations, only: %i[new create show destroy]
  end

  resources :comments
  resources :walking_reservations, only: [:index]

  get "dogs/:id/requests", to: "adopts#requests", as: :dog_requests

  # Defines the root path route ("/")
  root "pages#home"
  get "about", to: "pages#about"

  resources :placements

  resources :adoption_applications

  resources :shifts

  resources :donations

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :reports, only: %i[new create]

  get "profile", to: "pages#profile"
  resources :volunteers do
    collection do
      post :create_event
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user

    validates :name, :email, :message, presence: true

    after_create :send_report

    private

    def send_report
        ReportWorker.perform_async(id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_current_user

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user

    @report.save!
    redirect_to root_path, notice: t("contact_us.success_create")
  rescue StandardError => e
    flash.now[:alert] = e || t("contact_us.failed_create")
    render "reports/new", status: :unprocessable_entity
  end

  private

  def report_params
    params.require(:report).permit(:name, :email, :message)
  end

  def set_current_user
    @current_user = current_user
  end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/reports/_contacts.html.erb
    <h2>Feel free to contact us</h2>
    <p class="py-2 py-md-5">At et vehicula sodales est proin turpis pellentesque sinulla a aliquam 
    amet rhoncus quisque eget sit. Sociis blandit et pellentesque aliquet at quisque tortor lacinia nullam</p>
    <div class="d-flex flex-column gap-2">
        <div class="d-flex align-items-center gap-4">
            <%= image_tag 'location.svg' %>
            <p class="p-0 m-0">18015 Mytnytska str., Cherkasy, Ukraine</p>
        </div>
        <div class="d-flex align-items-center gap-4">
            <%= image_tag 'mail.svg' %>
            <p class="p-0 m-0"><%= link_to 'marsaua001@gmail.com', 'mailto:marsaua001@gmail.com' %></p>
        </div>
        <div class="d-flex align-items-center gap-4">
            <%= image_tag 'phone.svg' %>
            <p class="p-0 m-0">+380 98 288 46 18</p>
        </div>
        <div class="d-flex align-items-center gap-4">
            <%= image_tag 'clock.svg' %>
            <p class="p-0 m-0">Mon - Fri: 9AM - 6PM </p>
        </div>
    </div>

app/views/reports/_report_form.html.erb
<div class="flex-grow-1 flex-basis-0 min-w-0">
<%= form_for @report, method: :post, url: reports_path, local: true do |form| %>
    <div class="form-group mt-4">
        <%= form.label :name, 'Full Name', class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control', value: @current_user&.name %>
    </div>
    <div class="form-group mt-4">
        <%= form.label :email, 'Email', class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control', value: @current_user&.email %>
    </div>
    <div class="form-group mt-4">
        <%= form.label :message, 'Message', class: 'form-label' %>
        <%= form.text_area :message, class: 'form-control' %>
    </div>
    <%= form.submit 'Send', class: 'btn btn-primary mt-4' %>
<% end %>
</div>

app/views/reports/new.html.erb
<section class="back-img">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 order-2 order-md-1">
        <%= render 'reports/report_form'%>
      </div>
      <div class="col-12 col-md-6 order-1 order-md-2">
        <%= render 'reports/contacts'%>

      </div>
    </div>
    <div class="map-frame mt-5">
      <div id="map"
          data-lat="49.430895"
          data-lng="32.067994"
          data-zoom="13">
      </div>
    </div>
  </div>
</section>